# Generated by Django 5.2 on 2025-04-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryData',
            fields=[
                ('batchid', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.CharField(blank=True, null=True)),
                ('Duration', models.CharField(blank=True, null=True)),
                ('Alarms', models.IntegerField(blank=True, null=True)),
                ('Machine', models.CharField(blank=True, null=True)),
                ('Classification', models.CharField(blank=True, null=True)),
                ('Triggers', models.IntegerField(blank=True, null=True)),
                ('Device', models.CharField(blank=True, null=True)),
                ('abpcost', models.CharField(blank=True, null=True)),
                ('dosagecost', models.CharField(blank=True, null=True)),
                ('Weight', models.CharField(blank=True, null=True)),
                ('Dosings', models.IntegerField(blank=True, null=True)),
                ('pH', models.FloatField(blank=True, null=True)),
                ('tempdis', models.FloatField(blank=True, null=True)),
                ('temprange', models.FloatField(blank=True, null=True)),
                ('Customer', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
