# Generated by Django 5.2 on 2025-05-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApplication', '0002_batchlog_dailymaterials_dailyrecipes_energydata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(db_column='DATE', db_index=True, max_length=50)),
                ('washing_machine', models.CharField(db_column='Washing Machine', db_index=True, max_length=100)),
                ('program', models.FloatField(blank=True, db_column='PROGRAM', null=True)),
                ('time_to_fill', models.FloatField(blank=True, db_column='TIME TO FILL', null=True)),
                ('total_time', models.FloatField(blank=True, db_column='TOTAL TIME', null=True)),
                ('elec', models.FloatField(blank=True, db_column='ELEC', null=True)),
                ('water_1', models.FloatField(blank=True, db_column='WATER 1', null=True)),
                ('water_2', models.FloatField(blank=True, db_column='WATER 2', null=True)),
                ('gas', models.FloatField(blank=True, db_column='GAS', null=True)),
                ('chemical', models.FloatField(blank=True, db_column='CHEMICAL', null=True)),
                ('cost_per_kw', models.FloatField(blank=True, db_column='COST PER KW', null=True)),
                ('gas_cost', models.FloatField(blank=True, db_column='GAS COST', null=True)),
                ('water_cost', models.FloatField(blank=True, db_column='Water cost', null=True)),
                ('total', models.FloatField(blank=True, db_column='TOTAL', null=True)),
            ],
            options={
                'db_table': 'DisplayData',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaundryData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batchid', models.CharField(db_column='batchid', db_index=True, max_length=50)),
                ('time', models.CharField(db_column='Time', db_index=True, max_length=100)),
                ('duration', models.CharField(db_column='Duration', max_length=50)),
                ('alarms', models.TextField(blank=True, db_column='Alarms', null=True)),
                ('machine', models.CharField(blank=True, db_column='Machine', max_length=100, null=True)),
                ('classification', models.CharField(blank=True, db_column='Classification', max_length=100, null=True)),
                ('triggers', models.TextField(blank=True, db_column='Triggers', null=True)),
                ('device', models.CharField(blank=True, db_column='Device', max_length=100, null=True)),
                ('abpcost', models.CharField(blank=True, db_column='abpcost', max_length=50, null=True)),
                ('dosagecost', models.CharField(blank=True, db_column='dosagecost', max_length=50, null=True)),
                ('weight', models.CharField(blank=True, db_column='Weight', max_length=50, null=True)),
                ('dosings', models.CharField(blank=True, db_column='Dosings', max_length=10, null=True)),
                ('ph', models.CharField(blank=True, db_column='pH', max_length=50, null=True)),
                ('tempdis', models.CharField(blank=True, db_column='tempdis', max_length=50, null=True)),
                ('temprange', models.CharField(blank=True, db_column='temprange', max_length=50, null=True)),
                ('customer', models.CharField(blank=True, db_column='Customer', max_length=100, null=True)),
            ],
            options={
                'db_table': 'LaundryData',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='BatchLog',
        ),
        migrations.DeleteModel(
            name='DailyMaterials',
        ),
        migrations.DeleteModel(
            name='DailyRecipes',
        ),
        migrations.DeleteModel(
            name='EnergyData',
        ),
        migrations.DeleteModel(
            name='OEEDailyData',
        ),
        migrations.RemoveField(
            model_name='parsingschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='processedfile',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='processedfile',
            name='task',
        ),
        migrations.DeleteModel(
            name='PlantRunTime',
        ),
        migrations.AddIndex(
            model_name='displaydata',
            index=models.Index(fields=['date'], name='DisplayData_DATE_708c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='displaydata',
            index=models.Index(fields=['washing_machine'], name='DisplayData_Washing_d06204_idx'),
        ),
        migrations.AddIndex(
            model_name='laundrydata',
            index=models.Index(fields=['batchid'], name='LaundryData_batchid_d0b5ab_idx'),
        ),
        migrations.AddIndex(
            model_name='laundrydata',
            index=models.Index(fields=['time'], name='LaundryData_Time_aaa39a_idx'),
        ),
        migrations.AddIndex(
            model_name='laundrydata',
            index=models.Index(fields=['customer'], name='LaundryData_Custome_780e1c_idx'),
        ),
        migrations.DeleteModel(
            name='ParsingSchedule',
        ),
        migrations.DeleteModel(
            name='ParsingTask',
        ),
        migrations.DeleteModel(
            name='ProcessedFile',
        ),
    ]
