# Generated by Django 5.2 on 2025-05-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApplication', '0003_customer_displaydata_laundrydata_delete_batchlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WiFiNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_time', models.TimeField()),
                ('revert_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('last_switch', models.DateTimeField(blank=True, null=True)),
                ('primary_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_schedules', to='LaundryApplication.wifinetwork')),
                ('secondary_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_schedules', to='LaundryApplication.wifinetwork')),
            ],
        ),
    ]
