# Generated by Django 5.2.1 on 2025-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApplication', '0005_meterdata_remove_schedule_last_switch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdata',
            name='consumptionRecordId',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='meterdata',
            constraint=models.UniqueConstraint(fields=('consumptionRecordId',), name='unique_consumption_record'),
        ),
    ]
