# Generated by Django 5.2.1 on 2025-05-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApplication', '0006_meterdata_consumptionrecordid_and_more'),
    ]

    operations = [
    ]
