# Generated by Django 5.2.1 on 2025-05-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApplication', '0009_add_consumption_record_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meterdata',
            name='unique_consumption_record',
        ),
        migrations.AddConstraint(
            model_name='meterdata',
            constraint=models.UniqueConstraint(condition=models.Q(('consumptionRecordId__isnull', False)), fields=('consumptionRecordId',), name='unique_consumption_record'),
        ),
    ]
