# Generated by Django 5.2.1 on 2025-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApplication', '0010_remove_meterdata_unique_consumption_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utility Cost',
                'verbose_name_plural': 'Utility Costs',
                'ordering': ['-updated_at'],
            },
        ),
    ]
