# Generated by Django 5.2.1 on 2025-05-19 17:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryApplication', '0011_utilitycost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='utilitycost',
            options={},
        ),
        migrations.RemoveField(
            model_name='connectionlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='utilitycost',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='wifinetwork',
            name='name',
        ),
        migrations.RemoveField(
            model_name='wifinetwork',
            name='user',
        ),
        migrations.AddField(
            model_name='utilitycost',
            name='effective_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='wifinetwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='is_success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='connectionlog',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='revert_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='switch_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='utilitycost',
            name='electricity_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utilitycost',
            name='gas_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utilitycost',
            name='water_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wifinetwork',
            name='password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wifinetwork',
            name='ssid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
